In [3]:
import pandas as pd

economic_freedom = pd.read_excel(
    './files/index_economic_freedom_frasier_2000-2022.xlsx',
    skiprows=4
)
economic_freedom

,Unnamed: 0,Year,ISO Code 2,ISO Code 3,Countries,Economic Freedom Summary Index,Rank,Quartile,Government consumption,data,...,Tax compliance,Business regulations,Market openness,Business Permits,Distorton of the business environment,Freedom to enter markets and compete,Regulation,Area 5 Rank,World Bank Region,"World Bank Current Income Classification, 1990-Present"
0,NaN,2022.0,AL,ALB,Albania,7.48,38.0,1.0,8.282353,11.840000,...,3.587625,5.379721,6.810619,5.621940,6.250000,6.227520,6.897016,55.0,Europe & Central Asia,UM
1,NaN,2022.0,DZ,DZA,Algeria,4.46,161.0,4.0,3.491176,28.130000,...,4.764764,3.841924,4.641448,8.771111,2.583207,5.331922,4.508463,156.0,Middle East & North Africa,LM
2,NaN,2022.0,AO,AGO,Angola,4.79,155.0,4.0,7.944118,12.990000,...,4.641462,4.443797,3.427185,7.916416,1.250000,4.197867,5.302379,140.0,Sub-Saharan Africa,LM
3,NaN,2022.0,AR,ARG,Argentina,4.55,159.0,4.0,6.167647,19.030000,...,4.504147,4.969248,6.144822,5.726521,3.380395,5.083913,4.804769,148.0,Latin America & the Caribbean,UM
4,NaN,2022.0,AM,ARM,Armenia,7.49,36.0,1.0,7.058824,16.000000,...,6.020369,5.566860,5.590883,9.302574,5.000000,6.631152,7.095430,45.0,Europe & Central Asia,UM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4781,NaN,1970.0,VN,VNM,Vietnam,NaN,NaN,NaN,NaN,NaN,...,NaN,2.565000,NaN,NaN,NaN,NaN,NaN,NaN,East Asia & Pacific,NaN
4782,NaN,1970.0,YE,YEM,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,...,NaN,4.715000,NaN,NaN,NaN,NaN,NaN,NaN,Middle East & North Africa,NaN
4783,NaN,1970.0,ZM,ZMB,Zambia,5.28,65.0,3.0,3.448131,28.276353,...,NaN,6.377500,NaN,NaN,NaN,NaN,6.852414,33.0,Sub-Saharan Africa,NaN
4784,NaN,1970.0,ZW,ZWE,Zimbabwe,NaN,NaN,NaN,7.806922,13.456464,...,NaN,0.407500,NaN,NaN,NaN,NaN,NaN,NaN,Sub-Saharan Africa,NaN
4785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.778840,13.551945,...,NaN,5.010000,NaN,NaN,6.250000,6.250000,5.010822,104.0,NaN,NaN

In [23]:
economic_freedom.columns

Index(['Unnamed: 0', 'Year', 'ISO Code 2', 'ISO Code 3', 'Countries',
       ' Economic Freedom Summary Index', 'Rank', 'Quartile',
       'Government consumption', 'data', 'Transfers and subsidies', 'data.1',
       'Government investment', 'data.2', 'Top marginal income tax rate',
       'data.3', 'Top marginal income and payroll tax rate', 'data.4',
       'Top marginal tax rate', 'State ownership of Assets',
       'Size of Government', 'Area 1 Rank', 'Judicial independence',
       'Impartial courts', 'Protection of property rights',
       'Military interference in rule of law and politics',
       'Integrity of the legal system', 'Legal enforcement of contracts',
       'Regulatory restrictions on the sale of real property',
       'Reliability of police', 'Gender Legal Rights Adjustment',
       'Legal System & Property Rights -- Without Gender Adjustment',
       'Legal System & Property Rights -- With Gender Adjustment',
       'Area 2 Rank', 'Money growth', 'data.5',
       'Standard deviation of inflation', 'data.6',
       'Inflation: Most recent year', 'data.7',
       'Freedom to own foreign currency bank accounts', 'Sound Money',
       'Area 3 Rank', 'Revenue from trade taxes (% of trade sector)', 'data.8',
       'Mean tariff rate', 'data.9', 'Standard deviation of tariff rates',
       'data.10', 'Tariffs', 'Non-tariff trade barriers',
       'Compliance costs of importing and exporting',
       'Regulatory trade barriers', 'Black market exchange rates',
       'Financial openness', 'Capital controls',
       'Freedom of foreigners to visit', 'Protection of foreign assets',
       'Controls of the movement of capital and people',
       'Freedom to trade internationally', 'Area 4 Rank', 'Ownership of banks',
       'Private sector credit',
       'Interest rate controls/negative real interest rates)',
       'Credit market regulations', 'Hiring regulations and minimum wage',
       'Hiring and firing regulations', 'Centralized collective bargaining',
       'Hours Regulations', 'Mandated cost of worker dismissal',
       'Conscription', 'Foreign Labor', 'Labor market regulations',
       'Regulatory Burden', 'Bureacracy costs',
       'Impartial Public Administration', 'Tax compliance',
       'Business regulations', 'Market openness', 'Business Permits',
       'Distorton of the business environment',
       'Freedom to enter markets and compete', 'Regulation', 'Area 5 Rank',
       'World Bank Region',
       'World Bank Current Income Classification, 1990-Present'],
      dtype='object')

In [24]:
economic_freedom = (economic_freedom.drop(economic_freedom.columns[[0]], axis=1)
    .dropna(subset=['Year'])
    .astype({'Year': int})
)
economic_freedom.head(10)

,Year,ISO Code 2,ISO Code 3,Countries,Economic Freedom Summary Index,Rank,Quartile,Government consumption,data,Transfers and subsidies,...,Tax compliance,Business regulations,Market openness,Business Permits,Distorton of the business environment,Freedom to enter markets and compete,Regulation,Area 5 Rank,World Bank Region,"World Bank Current Income Classification, 1990-Present"
0,2022,AL,ALB,Albania,7.48,38.0,1.0,8.282353,11.840000,7.133515,...,3.587625,5.379721,6.810619,5.621940,6.250000,6.227520,6.897016,55.0,Europe & Central Asia,UM
1,2022,DZ,DZA,Algeria,4.46,161.0,4.0,3.491176,28.130000,7.817129,...,4.764764,3.841924,4.641448,8.771111,2.583207,5.331922,4.508463,156.0,Middle East & North Africa,LM
2,2022,AO,AGO,Angola,4.79,155.0,4.0,7.944118,12.990000,9.702997,...,4.641462,4.443797,3.427185,7.916416,1.250000,4.197867,5.302379,140.0,Sub-Saharan Africa,LM
3,2022,AR,ARG,Argentina,4.55,159.0,4.0,6.167647,19.030000,5.536785,...,4.504147,4.969248,6.144822,5.726521,3.380395,5.083913,4.804769,148.0,Latin America & the Caribbean,UM
4,2022,AM,ARM,Armenia,7.49,36.0,1.0,7.058824,16.000000,7.882834,...,6.020369,5.566860,5.590883,9.302574,5.000000,6.631152,7.095430,45.0,Europe & Central Asia,UM
5,2022,AU,AUS,Australia,7.98,9.0,1.0,2.605882,31.140000,6.313351,...,8.161510,7.292275,9.357153,8.953087,7.966810,8.759017,8.234082,6.0,East Asia & Pacific,H
6,2022,AT,AUT,Austria,7.62,23.0,1.0,3.329412,28.680000,2.980926,...,6.765789,6.332694,7.935145,7.296297,6.956506,7.395983,7.201002,40.0,Europe & Central Asia,H
7,2022,AZ,AZE,Azerbaijan,5.80,128.0,4.0,5.850000,20.110000,7.724796,...,5.799056,5.585355,4.743219,9.024510,3.750000,5.839243,6.115637,107.0,Europe & Central Asia,UM
8,2022,BS,BHS,"Bahamas, The",6.65,81.0,2.0,6.811765,16.840000,8.465940,...,6.631277,6.093416,8.004065,7.982034,6.250000,7.412033,7.338820,30.0,Latin America & the Caribbean,H
9,2022,BH,BHR,Bahrain,7.51,34.0,1.0,3.396608,28.451532,9.433243,...,9.873895,6.672702,8.051962,9.755027,5.688561,7.831850,7.635857,21.0,Middle East & North Africa,H

In [15]:
(economic_freedom
    .filter(items=['Year', 'Countries', ' Economic Freedom Summary Index', 'Rank'])
    .query('Countries == "Brazil"')
)

        Year Countries   Economic Freedom Summary Index   Rank
20    2022.0    Brazil                             6.56   85.0
185   2021.0    Brazil                             6.47   91.0
350   2020.0    Brazil                             6.41   98.0
515   2019.0    Brazil                             6.66   89.0
680   2018.0    Brazil                             6.68   88.0
845   2017.0    Brazil                             6.69   84.0
1010  2016.0    Brazil                             6.54   95.0
1175  2015.0    Brazil                             6.25  104.0
1340  2014.0    Brazil                             6.36   98.0
1505  2013.0    Brazil                             6.47   97.0
1670  2012.0    Brazil                             6.57   91.0
1835  2011.0    Brazil                             6.56   82.0
2000  2010.0    Brazil                             6.54   84.0
2165  2009.0    Brazil                             6.41   88.0
2330  2008.0    Brazil                             6.40   82.0
2495  2007.0    Brazil                             6.38   90.0
2660  2006.0    Brazil                             6.38   85.0
2825  2005.0    Brazil                             6.42   81.0
2990  2004.0    Brazil                             6.28   84.0
3155  2003.0    Brazil                             6.10   88.0
3320  2002.0    Brazil                             6.19   82.0
3485  2001.0    Brazil                             5.63  107.0
3650  2000.0    Brazil                             5.69  102.0
3815  1995.0    Brazil                             4.35  110.0
3980  1990.0    Brazil                             4.18   99.0
4145  1985.0    Brazil                             3.01  109.0
4310  1980.0    Brazil                             3.92   97.0
4475  1975.0    Brazil                             3.96   89.0
4640  1970.0    Brazil                             4.83   76.0

In [4]:
esg_data = pd.read_excel('files/dados_empresas_esg.xls')
esg_data.head(5)

,País,ID,Ticker,Name,Ano,GICSSETOR,G,ROA,QdeTobin,ESGBloomberg,...,ESGRefinitiv,Erefinitiv,Srefinitiv,Grefinitiv,LNTamanho,Alavancagem,ROA_w,QdeTobin_w,LNTamanho_w,Alavancagem_w
0,AfricaSul,15,EOHJ.J,EOH HOLDINGS LTD,2021,45,0,2.655522,1.325371,39.372299,...,59.093796,41.110134,50.419308,71.958588,19.233879,0.991020,2.655522,1.325371,19.233879,99.102032
1,AfricaSul,15,EOHJ.J,EOH HOLDINGS LTD,2020,45,0,1.018542,1.238941,38.748600,...,59.385960,40.441109,48.800453,74.184715,19.735004,0.970917,1.018542,1.238940,19.735004,97.091705
2,AfricaSul,28,NTCJ.J,NETCARE LTD,2011,35,0,-16.392294,1.430524,3.118400,...,34.744316,49.903507,26.242689,37.366665,22.395666,0.962779,-16.392294,1.430524,22.395666,96.277869
3,AfricaSul,15,EOHJ.J,EOH HOLDINGS LTD,2019,45,0,-13.033504,1.312458,37.370499,...,4.318662,44.582291,48.514427,38.180073,19.861603,0.938270,-13.033504,1.312458,19.861603,93.827015
4,AfricaSul,31,PIKJ.J,PICK N PAY STORES LTD,2020,30,0,6.831145,1.584352,4.694700,...,59.268078,71.226570,62.572525,44.432522,21.641808,0.910457,6.831145,1.584352,21.641808,91.045707

In [5]:
min_year = esg_data['Ano'].min()
max_year = esg_data['Ano'].max()

print(min_year, '-', max_year)

2005 - 2021

In [ ]:
freedom_filtered = economic_freedom.query(f"Year >= {min_year} and Year <= {max_year}")
print(freedom_filtered['Year'].min(), freedom_filtered['Year'].max())

2005 2021

## Dados descritivos ESG de países desenvolvidos e emergentes

In [ ]:
enterprises_esg_refinitiv_describe = esg_data.groupby('ID')['ESGRefinitiv'].describe().reset_index()

target_columns = [
    'País', 'Name', 'ID', 'G'
]

esg_target_group = esg_data.filter(items=target_columns).drop_duplicates(subset=['ID'])

described_enterprises = pd.merge(left=enterprises_esg_refinitiv_describe, right=esg_target_group, how='left', on='ID')
described_enterprises

,ID,count,mean,std,min,25%,50%,75%,max,País,Name,G
0,1,12.0,38.938109,21.726169,0.429229,31.005718,51.178417,52.414490,54.900562,AfricaSul,AVENG LTD,0
1,2,10.0,49.932894,26.078226,4.307252,46.532261,54.746237,69.921104,75.984634,AfricaSul,ALTRON LTD-A,0
2,3,12.0,55.619276,12.640813,39.304008,44.708216,55.557692,63.520675,74.400711,AfricaSul,ASPEN PHARMACARE HOLDINGS LT,0
3,4,12.0,49.938398,21.463452,5.776360,50.594406,54.744368,63.036998,71.271584,AfricaSul,AFRICAN RAINBOW MINERALS LTD,0
4,5,10.0,34.858236,16.521280,3.906715,38.421094,41.235329,44.166487,47.445747,AfricaSul,ASTRAL FOODS LTD,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3505,3576,14.0,61.314190,16.450290,6.378551,61.623383,65.151810,67.585905,74.534668,Turquia,TUPRAS-TURKIYE PETROL RAFINE,0
3506,3577,9.0,64.348765,20.155894,23.359735,65.451981,71.209206,73.145935,85.284584,Turquia,ULKER BISKUVI SANAYI,0
3507,3578,2.0,72.924885,5.330129,69.155914,71.040400,72.924885,74.809370,76.693855,Turquia,VESTEL BEYAZ ESYA SANAYI VE,0
3508,3579,4.0,69.562288,4.204078,65.780487,66.563789,68.706615,71.705114,75.055435,Turquia,VESTEL ELEKTRONIK SANAYI,0
3509,3580,4.0,56.114965,14.439385,42.362488,44.310925,56.296425,68.100466,69.504524,Turquia,ZORLU ENERJI ELEKTRIK URETIM,0

In [76]:
(described_enterprises
 .assign(Emergente=described_enterprises['G'].apply(lambda x: 'Sim' if x == 0 else 'Não'))
 .drop(columns=['G'])
 .rename(columns={
     'ID': 'id',
     'País': 'country',
     'Name': 'name',
     'Emergente': 'emergent'
 })
 .to_excel('results/empresas_dados_descritivos_refinitiv.xlsx', index=False)
)

## Describe do ESGRefinitiv dos Países

In [6]:
country_esg_refinitiv_describe = esg_data.groupby('País')['ESGRefinitiv'].describe().reset_index()
country_esg_refinitiv_describe

,País,count,mean,std,min,25%,50%,75%,max
0,AfricaSul,508.0,47.562497,20.878818,4.292287e-01,36.914800,51.053305,61.656567,95.658554
1,Alemanha,1286.0,50.176929,25.497472,1.642512e-01,31.708312,51.684885,72.006842,99.810516
2,ArabiaSaudita,93.0,34.957261,21.524533,1.895864e-01,16.924181,31.186167,51.657566,92.656090
3,Argentina,62.0,48.859104,18.002976,5.923722e-01,43.734541,52.032358,60.250853,80.379616
4,Australia,1853.0,36.555366,22.807633,1.000000e-08,18.901878,32.836327,52.705299,99.346405
5,Brasil,741.0,48.611529,23.116136,5.957524e-02,34.090645,52.818703,66.450523,94.743011
6,Canada,324.0,39.223351,20.822756,4.415210e-01,25.156545,39.675226,53.819322,88.386475
7,China,1558.0,30.318530,17.557042,1.000000e-08,18.795472,28.362140,39.601820,99.149475
8,CoreiaSul,1122.0,46.568496,26.175321,1.000000e-08,20.692628,53.061224,67.279705,99.382584
9,EUA,9354.0,40.151669,22.807216,1.000000e-08,23.338934,37.176872,57.610194,98.795609
10,Franca,1207.0,55.118274,23.736164,4.357186e-02,41.568338,60.351028,74.114216,91.756958
11,India,785.0,44.939227,23.754137,2.695592e-01,24.540749,46.986828,62.291557,92.748253
12,Indonesia,370.0,43.705293,23.194129,3.345525e-01,26.632334,45.142775,60.393063,99.573601
13,Italia,418.0,56.881398,22.605411,6.960254e-02,45.088418,60.728821,73.613085,92.717239
14,Japao,4482.0,44.193226,23.228042,0.000000e+00,26.307516,45.852619,62.176357,99.960823
15,Mexico,315.0,48.175680,24.565186,5.786764e-01,26.972215,50.728973,65.934727,97.472527
16,ReinoUnido,2757.0,49.201570,22.853240,2.887265e-02,34.483078,51.445572,66.014259,95.741455
17,Russia,349.0,41.570137,20.427859,2.081570e-01,28.898066,42.591866,56.505638,96.537163
18,Turquia,262.0,54.188248,24.153554,1.332622e+00,36.011825,61.733072,72.135201,92.815514

In [7]:
country_esg_refinitiv_describe.to_excel('results/paises_dados_descritivos_refinitiv.xlsx', index=False)